### ISSUE TITLE
android 4.0x cannot show action name

### ISSUE THREAD

**Issue by browsnet** [SamThompson/BubbleActions#14]
because you set the action name in BubbleActionOverlay.setupOverlay , the textview layout width is zero, so we cannot see the action name.

for fix this bug, just change the bubble.actions.bubble.item.xml, and add one line to the TextView

android:text="placeholder"

I hope you fix it and upload to jcenter quickly, thank you.

**Comment by SamThompson** [comment]
I'm currently looking into this and a couple of other compatibility issues. Thanks for reporting!
