### ISSUE TITLE
Bubble are not showing on Android 9.0 Devices

### ISSUE THREAD

**Issue by asadmukhtar28** [SamThompson/BubbleActions#32]
Hi,

I use bubble actions in our App, that works fine on below 9.0 devices, when i run my app on Android 9.0 Device (M1 A2 Lite) all things fine but Bubble Actions are not showing.

Thanks

**Comment by srikoushik** [comment]
Yes, even with "Honor View 10"

**Comment by SureshSc** [comment]
i am facing same issue, when we will get update @SamThompson

**Comment by kiiryuuuu** [comment]
Please help @SamThompson we really like your creationn

**Comment by pnkram** [comment]
I solved the problem thanks to this post: https://stackoverflow.com/a/52561294
I manually imported the library then I edited the class BubbleActionOverlay. Instead of dragShadowBuilder I created another object using the class MyDragShadowBuilder() which is in the post I linked.

**Comment by oremlawi** [comment]
According to @pnkram 's answer yes, it worked, all what you need is to create this class:

```
package com.samthompson.bubbleactions;

import android.graphics.Point;
import android.view.View;

public class MyDragShadowBuilder extends View.DragShadowBuilder {

    @Override
    public void onProvideShadowMetrics(Point outShadowSize, Point outShadowTouchPoint) {
        outShadowSize.set(1,1);
        outShadowTouchPoint.set(0,0);
    }
}
```

Then from BubbleActionOverlay class you need to replace these two lines:
```
private DragShadowBuilder dragShadowBuilder;
dragShadowBuilder = new DragShadowBuilder();
```

by these two lines:
```
private MyDragShadowBuilder dragShadowBuilder;
dragShadowBuilder = new MyDragShadowBuilder();
```
