### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by zyyoona7** [SamThompson/BubbleActions#9]
I am Chinese,English is bad.
Press exhaled BubbleActions, when the animation has not been completed, the finger off the screen quickly. Pages will be stuck, BubbleActions can not hide. Appear absolutely
长按呼出BubbleActions ，当animation没有执行完毕的时候，手指快速离开屏幕。页面会卡住，BubbleActions 不能隐藏。百分之百出现

**Comment by SamThompson** [comment]
Was this experienced on the sample app?
